#! /bin/bash

# Check our system.

echo "Memory: "

# free tells us how much memory we're using
# To be a real pro we can put the full path to commands 
# we can't assume all users will have same PATH
/usr/bin/free -h

echo "Disk Usage: "
/usr/bin/df -h

echo "Uptime: "
uptime

exit
